Controllers/UploadDataController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserManagementApp.Models;

namespace UserManagementApp.Controllers
{
    [Authorize]
    public class UploadDataController : Controller
    {

        private UsersManagementEntities db = new UsersManagementEntities();

        public ActionResult Create()
        {
            return View(new List<UploadDetail>());
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase postedFile)
        {
            List<UploadDetail> uploadData = new List<UploadDetail>();

            string filePath = string.Empty;
            if (postedFile != null)
            {
                string path = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                filePath = path + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);
                postedFile.SaveAs(filePath);

                //Create a DataTable.
                DataTable dt = new DataTable();
                dt.Columns.AddRange(new DataColumn[7] {
                                new DataColumn("TerminalId", typeof(int)),
                                new DataColumn("SerialNo", typeof(int)),
                                new DataColumn("MerchantId", typeof(int)),
                                new DataColumn("Description",typeof(string)),
                                new DataColumn("Manufacturer",typeof(string)),
                                new DataColumn("Model",typeof(string)),
                                new DataColumn("State",typeof(string))
                });


                //Read the contents of CSV file.
                string csvData = System.IO.File.ReadAllText(filePath);

                String[] rows = csvData.Split('\n');
                int len = rows.Length;
                if (len > 1)
                {
                    //Execute a loop over the rows.
                    for(int i=0; i < len; i++)
                    {
                        // Skip header
                        if (i == 0) continue;

                        String row = rows[i];
                        if (!string.IsNullOrEmpty(row))
                        {
                            dt.Rows.Add();
                            int j = 0;

                            String[] cells = row.Split(',');

                            //Execute a loop over the columns and prepare datatable
                            foreach (string cell in cells)
                            {
                                dt.Rows[dt.Rows.Count - 1][j] = cell;
                                j++;
                            }

                            //Add into return list
                            uploadData.Add(new UploadDetail
                            {
                                TerminalId = Convert.ToInt32(row.Split(',')[0]),
                                SerialNo = Convert.ToInt32(row.Split(',')[1]),
                                MerchantId = Convert.ToInt32(row.Split(',')[2]),
                                Description = row.Split(',')[3],
                                Manufacturer = row.Split(',')[4],
                                Model = row.Split(',')[5],
                                State = row.Split(',')[6]
                            });
                        }
                    }

                    using (var context = new UsersManagementEntities())
                    {
                        using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy((context.Database.Connection) as SqlConnection))
                        {
                            //Set the database table name.
                            sqlBulkCopy.DestinationTableName = "dbo.UploadData";

                            //[OPTIONAL]: Map the DataTable columns with that of the database table
                            sqlBulkCopy.ColumnMappings.Add("TerminalId", "TerminalId");
                            sqlBulkCopy.ColumnMappings.Add("SerialNo", "SerialNo");
                            sqlBulkCopy.ColumnMappings.Add("MerchantId", "MerchantId");
                            sqlBulkCopy.ColumnMappings.Add("Description", "Description");
                            sqlBulkCopy.ColumnMappings.Add("Manufacturer", "Manufacturer");
                            sqlBulkCopy.ColumnMappings.Add("Model", "Model");
                            sqlBulkCopy.ColumnMappings.Add("State", "State");

                            context.Database.Connection.Open();
                            sqlBulkCopy.WriteToServer(dt);
                            context.Database.Connection.Close();
                        }
                    }
                }
            }

            return View(uploadData);
        }


        public ActionResult UploadFileList()
        {
            return View(db.UploadData.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            UploadData uploadData = db.UploadData.Find(id);
            if (uploadData == null)
            {
                return HttpNotFound();
            }
            return View(uploadData);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UploadData uploadData = db.UploadData.Find(id);
            if (uploadData == null)
            {
                return HttpNotFound();
            }
            return View(uploadData);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UploadData uploadData = db.UploadData.Find(id);
            db.UploadData.Remove(uploadData);
            db.SaveChanges();
            return RedirectToAction("UploadFileList");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UploadData uploadData = db.UploadData.Find(id);
            if (uploadData == null)
            {
                return HttpNotFound();
            }
            return View(uploadData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TerminalId,SerialNo,MerchantId,Description,Manufacturer,State,Model")] UploadData uploadData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uploadData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UploadFileList");
            }
            return View(uploadData);
        }

    }



}

Views/UploadData/Create.cshtml
@using UserManagementApp.Models
@model IEnumerable<UploadDetail>
@{

    ViewBag.Title = "UploadFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="">
        <div class="row">
            <div class="col-md-12">

                <div class="row">

                    <div class="col-md-4">
                        @using (Html.BeginForm("Create", "UploadData", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <h4 class="text-center">Import File</h4>
                            <div class="row">
                                <div class="col-md-12">
                                    <label>File Upload (<a href="~/Files/SampleFile.csv" download>Download Sample File</a>)</label>
                                    <div class="form-group">
                                        <input type="file" name="postedFile" id="postedFile" />
                                    </div>
                                </div>

                            </div>

                            <div class="row">

                                <div class="col-md-12">

                                    <div class="form-group">
                                        <input type="submit" value="Import" id="btn_upload" />
                                    </div>
                                </div>
                            </div>

                        }
                    </div>

                    <div class="col-md-8">
                        <h4 class="text-center">Imported Data</h4>
                        <div class="row">
                            <div class="col-md-12">

                                <table id="DataTable" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Terminal ID</th>
                                            <th>Serial No</th>
                                            <th>Merchant ID</th>
                                            <th>Description</th>
                                            <th>Manufacturer</th>
                                            <th>Model</th>
                                            <th>State</th>
                                        </tr>
                                    </thead>
                                    @if (Model.Count() > 0)
                                    {
                                        <tbody>
                                            @foreach (UploadDetail uploadDetail in Model)
                                            {
                                                <tr>
                                                    <td>@uploadDetail.TerminalId</td>
                                                    <td>@uploadDetail.SerialNo</td>
                                                    <td>@uploadDetail.MerchantId</td>
                                                    <td>@uploadDetail.Description</td>
                                                    <td>@uploadDetail.Manufacturer</td>
                                                    <td>@uploadDetail.Model</td>
                                                    <td>@uploadDetail.State</td>
                                                </tr>
                                            }
                                        </tbody>
                                    }
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "UploadFileList")
</div>

Views/UploadData/Delete.cshtml
@model UserManagementApp.UploadData

@{
    ViewBag.Title = "Delete Import Data"; 
}

<h2>Delete Import Data</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TerminalId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TerminalId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MerchantId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MerchantId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "UploadFileList")
        </div>
    }
</div>

Views/UploadData/Details.cshtml
@model UserManagementApp.UploadData

<div>
    <h4>View Import Data</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TerminalId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TerminalId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MerchantId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MerchantId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "UploadFileList")
</p>

Views/UploadData/Edit.cshtml
@model UserManagementApp.UploadData

@{
    ViewBag.Title = "Edit Import Data";
}

<h2>Edit Import Data</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TerminalId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TerminalId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TerminalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SerialNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerialNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MerchantId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MerchantId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MerchantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "UploadFileList")
</div>

Views/UploadData/UploadFileList.cshtml
@model IEnumerable<UserManagementApp.UploadData>

@{
    ViewBag.Title = "Imported Data List";
}

<div>
    <h4 class="text-center">Imported Data List</h4>
</div>
<div style="float:right;">
    <p>
        @Html.ActionLink("Import File", "Create")
    </p>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TerminalId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SerialNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MerchantId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.TerminalId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SerialNo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MerchantId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Description)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Manufacturer)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Model)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.State)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
    </td>
</tr>
}

</table>